quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pagamentosdb}
      max-size: 16

  hibernate-orm:
    database:
      generation: update

  rest-client:
    api-pagamento-externo:
      url: ${PAGAMENTO_EXTERNO_URL:http://localhost:8089}
      connection-timeout: 5000
      read-timeout: 10000
    logging:
      scope: all
      body-limit: 1024
  log:
    category:
      "io.quarkus.rest.client.logging":
        level: DEBUG

  jackson:
    # Evita falhas caso o JSON venha com propriedades a mais que não estão no POJO
    fail-on-unknown-properties: false

#api-pagamento-externo/mp-rest/url: ${PAGAMENTO_EXTERNO_URL:http://localhost:8081}

mp:
  messaging:
    incoming:
      "pedido.criado":
        connector: smallrye-kafka
        topic: pedido.criado # talvez receber por variavel de ambiente
        group:
          id: pagamentos-worker-group
        auto:
          offset:
            reset: earliest

kafka:
  bootstrap:
    servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}