quarkus:
  application:
    name: chef-payment-service
  datasource:
    db-kind: postgresql
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pagamentosdb}
      max-size: 16

  hibernate-orm:
    schema-management:
      strategy: update

  rest-client:
    api-pagamento-externo:
      url: ${PAGAMENTO_EXTERNO_URL:http://localhost:8089}
      read-timeout: 5000
      connect-timeout: 2000
    logging:
      scope: all
      body-limit: 1024

  log:
    category:
      "io.quarkus.rest.client.logging":
        level: INFO
      "io.smallrye.faulttolerance":
        level: INFO
      "io.smallrye.reactive.messaging.kafka":
        level: INFO
      "org.apache.kafka":
        level: WARN

  jackson:
    # Evita falhas caso o JSON venha com propriedades a mais que não estão no POJO
    fail-on-unknown-properties: false

smallrye:
  messaging:
    worker:
      pedido-pool:
        max-concurrency: 16 # número máximo de threads que podem processar mensagens simultaneamente
      pagamento-pool:
        max-concurrency: 16 # pool dedicado para processamento de pagamentos

mp:
  messaging:
    incoming:
      "pedido-criado-in":
        connector: smallrye-kafka
        topic: pedido.criado
        max.poll.interval.ms: 900000        # 15 minutos para evitar rebalance em processamento longo
        commit-strategy: throttled          # Faz commit de offsets em lote para reduzir overhead
        concurrency: 4                      # cria múltiplos consumidores paralelos
        group:
          id: pedido-criado-service             # Consumer group que permite balanceamento entre instâncias do serviço
        auto:
          offset:
            reset: earliest                 # fará com que o serviço leia todas as mensagens antigas presas no tópico assim que reiniciar
      "pagamento-pendente-in":
        connector: smallrye-kafka
        topic: pagamento.pendente
        max.poll.interval.ms: 900000        # 15 minutos para evitar rebalance em processamento longo
        commit-strategy: throttled          # Faz commit de offsets em lote para reduzir overhead
        concurrency: 4                      # cria múltiplos consumidores paralelos
        group:
          id: pagamento-pendente-service             # Consumer group que permite balanceamento entre instâncias do serviço
        auto:
          offset:
            reset: earliest                 # fará com que o serviço leia todas as mensagens antigas presas no tópico assim que reiniciar

    outgoing:
      "pagamento-pendente-out":
        connector: smallrye-kafka
        topic: pagamento.pendente

      "pagamento-aprovado-out":
        connector: smallrye-kafka
        topic: pagamento.aprovado


kafka:
  bootstrap:
    servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}