quarkus:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pagamentosdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  hibernate-orm:
    database:
      generation: update

mp:
  messaging:
    incoming:
      solicitacoes-pagamentos:
        connector: smallrye-kafka
        topic: solicitacoes-pagamentos # talvez receber por variavel de ambiente
        value:
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
        group:
          id: pagamentos-worker-group